# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio_4.xdc

# Block Designs: bd/Stopwatch_design/Stopwatch_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design || ORIG_REF_NAME==Stopwatch_design} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_microblaze_0_1/Stopwatch_design_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_microblaze_0_1 || ORIG_REF_NAME==Stopwatch_design_microblaze_0_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_dlmb_v10_1/Stopwatch_design_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_dlmb_v10_1 || ORIG_REF_NAME==Stopwatch_design_dlmb_v10_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_ilmb_v10_1/Stopwatch_design_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_ilmb_v10_1 || ORIG_REF_NAME==Stopwatch_design_ilmb_v10_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_dlmb_bram_if_cntlr_1/Stopwatch_design_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Stopwatch_design_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_ilmb_bram_if_cntlr_1/Stopwatch_design_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Stopwatch_design_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_lmb_bram_1/Stopwatch_design_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_lmb_bram_1 || ORIG_REF_NAME==Stopwatch_design_lmb_bram_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_mdm_1_1/Stopwatch_design_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_mdm_1_1 || ORIG_REF_NAME==Stopwatch_design_mdm_1_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_clk_wiz_1_1/Stopwatch_design_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_clk_wiz_1_1 || ORIG_REF_NAME==Stopwatch_design_clk_wiz_1_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_rst_clk_wiz_1_100M_1/Stopwatch_design_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==Stopwatch_design_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_axi_uartlite_0_1/Stopwatch_design_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_axi_uartlite_0_1 || ORIG_REF_NAME==Stopwatch_design_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_xbar_0/Stopwatch_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_xbar_0 || ORIG_REF_NAME==Stopwatch_design_xbar_0} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_microblaze_0_axi_periph_1/Stopwatch_design_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_microblaze_0_axi_periph_1 || ORIG_REF_NAME==Stopwatch_design_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_gpio_0_0/Stopwatch_design_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_gpio_0_0 || ORIG_REF_NAME==Stopwatch_design_gpio_0_0} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_gpio_1_0/Stopwatch_design_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_gpio_1_0 || ORIG_REF_NAME==Stopwatch_design_gpio_1_0} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_gpio_2_0/Stopwatch_design_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_gpio_2_0 || ORIG_REF_NAME==Stopwatch_design_gpio_2_0} -quiet] -quiet

# IP: bd/Stopwatch_design/ip/Stopwatch_design_gpio_3_0/Stopwatch_design_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Stopwatch_design_gpio_3_0 || ORIG_REF_NAME==Stopwatch_design_gpio_3_0} -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_microblaze_0_1/Stopwatch_design_microblaze_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_microblaze_0_1 || ORIG_REF_NAME==Stopwatch_design_microblaze_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_microblaze_0_1/Stopwatch_design_microblaze_0_1_ooc_debug.xdc

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_lmb_bram_1/Stopwatch_design_lmb_bram_1_ooc.xdc

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_mdm_1_1/Stopwatch_design_mdm_1_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_mdm_1_1 || ORIG_REF_NAME==Stopwatch_design_mdm_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_mdm_1_1/Stopwatch_design_mdm_1_1_ooc_trace.xdc

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_clk_wiz_1_1/Stopwatch_design_clk_wiz_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_clk_wiz_1_1 || ORIG_REF_NAME==Stopwatch_design_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_clk_wiz_1_1/Stopwatch_design_clk_wiz_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_clk_wiz_1_1 || ORIG_REF_NAME==Stopwatch_design_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_clk_wiz_1_1/Stopwatch_design_clk_wiz_1_1_ooc.xdc

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_rst_clk_wiz_1_100M_1/Stopwatch_design_rst_clk_wiz_1_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==Stopwatch_design_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_rst_clk_wiz_1_100M_1/Stopwatch_design_rst_clk_wiz_1_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==Stopwatch_design_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_axi_uartlite_0_1/Stopwatch_design_axi_uartlite_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_axi_uartlite_0_1 || ORIG_REF_NAME==Stopwatch_design_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_axi_uartlite_0_1/Stopwatch_design_axi_uartlite_0_1_ooc.xdc

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/ip/Stopwatch_design_axi_uartlite_0_1/Stopwatch_design_axi_uartlite_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Stopwatch_design_axi_uartlite_0_1 || ORIG_REF_NAME==Stopwatch_design_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/0623_Prectice_Custom_IP/0623_Prectice_Custom_IP.gen/sources_1/bd/Stopwatch_design/Stopwatch_design_ooc.xdc
