# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio.xdc

# Block Designs: bd/GPIO_Test/GPIO_Test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test || ORIG_REF_NAME==GPIO_Test} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_microblaze_0_0/GPIO_Test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_microblaze_0_0 || ORIG_REF_NAME==GPIO_Test_microblaze_0_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_dlmb_v10_0/GPIO_Test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_dlmb_v10_0 || ORIG_REF_NAME==GPIO_Test_dlmb_v10_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_ilmb_v10_0/GPIO_Test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_ilmb_v10_0 || ORIG_REF_NAME==GPIO_Test_ilmb_v10_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_dlmb_bram_if_cntlr_0/GPIO_Test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==GPIO_Test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_ilmb_bram_if_cntlr_0/GPIO_Test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==GPIO_Test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_lmb_bram_0/GPIO_Test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_lmb_bram_0 || ORIG_REF_NAME==GPIO_Test_lmb_bram_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_mdm_1_0/GPIO_Test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_mdm_1_0 || ORIG_REF_NAME==GPIO_Test_mdm_1_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_clk_wiz_1_0/GPIO_Test_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_clk_wiz_1_0 || ORIG_REF_NAME==GPIO_Test_clk_wiz_1_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_rst_clk_wiz_1_100M_0/GPIO_Test_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==GPIO_Test_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_axi_uartlite_0_0/GPIO_Test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_axi_uartlite_0_0 || ORIG_REF_NAME==GPIO_Test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_xbar_0/GPIO_Test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_xbar_0 || ORIG_REF_NAME==GPIO_Test_xbar_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_microblaze_0_axi_periph_0/GPIO_Test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==GPIO_Test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/GPIO_Test/ip/GPIO_Test_gpio_0_0/GPIO_Test_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_Test_gpio_0_0 || ORIG_REF_NAME==GPIO_Test_gpio_0_0} -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_microblaze_0_0/GPIO_Test_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_microblaze_0_0 || ORIG_REF_NAME==GPIO_Test_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_microblaze_0_0/GPIO_Test_microblaze_0_0_ooc_debug.xdc

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_lmb_bram_0/GPIO_Test_lmb_bram_0_ooc.xdc

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_mdm_1_0/GPIO_Test_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_mdm_1_0 || ORIG_REF_NAME==GPIO_Test_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_mdm_1_0/GPIO_Test_mdm_1_0_ooc_trace.xdc

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_clk_wiz_1_0/GPIO_Test_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_clk_wiz_1_0 || ORIG_REF_NAME==GPIO_Test_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_clk_wiz_1_0/GPIO_Test_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_clk_wiz_1_0 || ORIG_REF_NAME==GPIO_Test_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_clk_wiz_1_0/GPIO_Test_clk_wiz_1_0_ooc.xdc

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_rst_clk_wiz_1_100M_0/GPIO_Test_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==GPIO_Test_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_rst_clk_wiz_1_100M_0/GPIO_Test_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==GPIO_Test_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_axi_uartlite_0_0/GPIO_Test_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_axi_uartlite_0_0 || ORIG_REF_NAME==GPIO_Test_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_axi_uartlite_0_0/GPIO_Test_axi_uartlite_0_0_ooc.xdc

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/ip/GPIO_Test_axi_uartlite_0_0/GPIO_Test_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_Test_axi_uartlite_0_0 || ORIG_REF_NAME==GPIO_Test_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Work/OnDeviceAI2/260622_MicroBlaze_GPIO/260622_MicroBlaze_GPIO.gen/sources_1/bd/GPIO_Test/GPIO_Test_ooc.xdc
